apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
        - image: olehzahnitko/argocd:1.1.35
          name: testapi
          ports:
            - containerPort: 1700
