apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
spec:
  replicas: 4
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - image: andriicodefresh/argocd:1.2.16
          name: test-api
          ports:
            - containerPort: 1700
